In [49]:
#Exploration of some NumPy 

In [50]:

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [51]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)


In [ ]:
# 1D NumPy Array
bmi = np_weight / np_height ** 2
bmi

In [ ]:
#NumPy array contains only one data type
np.array([1.0, "is", True])

In [ ]:
#Different types: different behavior!
python_list = [1, 2, 3]
python_list + python_list

In [ ]:
#Different types: different behavior!
numpy_array = np.array([1, 2, 3])
numpy_array + numpy_array

In [ ]:
bmi

In [ ]:
#NumPy subsetting
bmi[1]

In [ ]:
#NumPy subsetting
bmi > 23

In [52]:
#NumPy subsetting
bmi[bmi > 23]

array([24.7473475])

In [53]:
# 2D Numpy Arrays
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
print(type(np_height))
print(type(np_weight))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [54]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [55]:
np_2d.shape

(2, 5)

In [56]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [57]:
#NumPy array contains only one data type
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
[65.4, 59.2, 63.6, 88.4, "68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [58]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [59]:
np_2d[0][2]

1.71

In [60]:
np_2d[0,2]

1.71

In [61]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [62]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [63]:
np_city =np.array([[1.64, 71.78],[1.37, 63.35], [1.6 , 55.09],[2.04, 74.85], [2.04, 68.72], [2.01, 73.57]])

In [64]:
np.mean(np_city[:,0])

1.7833333333333332

In [65]:
np.median(np_city[:,0])

1.8249999999999997

In [66]:
np.mean(np_city[:,1])

67.89333333333333

In [67]:
np.median(np_city[:,1])

70.25

In [68]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[1.        , 0.64924262],
       [0.64924262, 1.        ]])

In [69]:
np.std(np_city[:,0])

0.2608107018935807

In [70]:
np_city[:,0].sum()

10.7

In [71]:
np_city[:,0].sort()

In [72]:
np_city[:,0]

array([1.37, 1.6 , 1.64, 2.01, 2.04, 2.04])

In [73]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[1.        , 0.40225613],
       [0.40225613, 1.        ]])

In [74]:
np_city[:,1].sort()

In [75]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[1.        , 0.94596445],
       [0.94596445, 1.        ]])

In [76]:
#Generate data
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [77]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [78]:
height

array([1.68, 1.9 , 1.44, ..., 2.2 , 1.53, 1.8 ])

In [79]:
weight

array([88.88, 63.08, 66.05, ..., 67.3 , 53.45, 34.32])

In [80]:
np_city = np.column_stack((height, weight))

In [81]:
np_city

array([[ 1.68, 88.88],
       [ 1.9 , 63.08],
       [ 1.44, 66.05],
       ...,
       [ 2.2 , 67.3 ],
       [ 1.53, 53.45],
       [ 1.8 , 34.32]])

In [82]:
city = np.row_stack((height, weight))

In [83]:
city

array([[ 1.68,  1.9 ,  1.44, ...,  2.2 ,  1.53,  1.8 ],
       [88.88, 63.08, 66.05, ..., 67.3 , 53.45, 34.32]])